version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - sql_storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: reports
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootrootroot
    command: server --console-address ":9001" /data
  

volumes:
  sql_storage: {}
  minio_storage: {}